api:
  token: FsaGHWa312t19jgSG2qa2agsSG82gsnag383gSn2aSgn218Gxawg
  debug: True
  api: True

httpserver:
  api_url: 'http://<Django API IP>:8000/api/http/'
  listener_ip: 0.0.0.0
  listener_port: 80
  debug: True
  api: True

httpsserver:
  api_url: 'http://<Django API IP>:8000/api/https/'
  listener_ip: 0.0.0.0
  listener_port: 443
  debug: True
  api: True
  crt_file: 'localhost.pem'

pcap:
  api_url: 'http://<Django API IP>:8000/api/pcap/'
  api: True
  print_pcap: True
  print_payload: True
  debug: True

dnsserver:
  api_url: 'http://<Django API IP}:8000/api/dns/'
  listener_ip: 0.0.0.0
  listener_port: 53
  return_ip: <your IP address>
  debug: True
  api: True
